module;
#include "vulkan/vulkan.h"
module Aether:VulkanContext;
import :VulkanContext;
import :EngineDefinition;
import :RHIContext;
import :Log;
import :Error;
import :VulkanDebug;
import :VulkanDefinition;

namespace Aether
{
	static std::string s_EngineName = "AetherEngine_Vulkan";

    VulkanContext::VulkanContext(AetherEngine* engine)
        :RHIContext(engine)
    {

    }

    AResult VulkanContext::Init()
    {
		AETHER_RETIF_FAIL(this->CreateVulkanInstance());
		AETHER_RETIF_FAIL(this->CreatePhysicalDevices());

		return A_Success;
    };












    AResult VulkanContext::CreateVulkanInstance()
    {
		std::vector<const char*> instanceExtensions = { VK_KHR_SURFACE_EXTENSION_NAME };

		// Enable surface extensions depending on os
#if defined(AETHER_PLATFORM_WINDOWS)
		//instanceExtensions.push_back(VK_KHR_WIN32_SURFACE_EXTENSION_NAME);
#endif

		// Get extensions supported by the instance and store for later use
		uint32_t extCount = 0;
		vkEnumerateInstanceExtensionProperties(nullptr, &extCount, nullptr);
		if (extCount > 0)
		{
			std::vector<VkExtensionProperties> extensions(extCount);
			if (vkEnumerateInstanceExtensionProperties(nullptr, &extCount, &extensions.front()) == VK_SUCCESS)
			{
				for (VkExtensionProperties& extension : extensions)
				{
					supportedInstanceExtensions.push_back(extension.extensionName);
				}
			}
		}

		// Enabled requested instance extensions
		if (!enabledInstanceExtensions.empty())
		{
			for (const char* enabledExtension : enabledInstanceExtensions)
			{
				// Output message if requested extension is not available
				if (std::find(supportedInstanceExtensions.begin(), supportedInstanceExtensions.end(), enabledExtension) == supportedInstanceExtensions.end())
				{
					std::cerr << "Enabled instance extension \"" << enabledExtension << "\" is not present at instance level\n";
				}
				instanceExtensions.push_back(enabledExtension);
			}
		}

		// Shaders generated by Slang require a certain SPIR-V environment that can't be satisfied by Vulkan 1.0, so we need to expliclity up that to at least 1.1 and enable some required extensions
		//if (shaderDir == "slang") {
		//	if (apiVersion < VK_API_VERSION_1_1) {
		//		apiVersion = VK_API_VERSION_1_1;
		//	}
		//	enabledDeviceExtensions.push_back(VK_KHR_SPIRV_1_4_EXTENSION_NAME);
		//	enabledDeviceExtensions.push_back(VK_KHR_SHADER_FLOAT_CONTROLS_EXTENSION_NAME);
		//	enabledDeviceExtensions.push_back(VK_KHR_SHADER_DRAW_PARAMETERS_EXTENSION_NAME);
		//}

		VkApplicationInfo appInfo{
			.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
			.pApplicationName = s_EngineName.c_str(),
			.pEngineName = s_EngineName.c_str(),
			.apiVersion = VK_API_VERSION_1_1
		};

		VkInstanceCreateInfo instanceCreateInfo{
			.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
			.pApplicationInfo = &appInfo
		};

		VkDebugUtilsMessengerCreateInfoEXT debugUtilsMessengerCI{};
		//if (settings.validation) 
		{
			VulkanDebug::setupDebugingMessengerCreateInfo(debugUtilsMessengerCI);
			debugUtilsMessengerCI.pNext = instanceCreateInfo.pNext;
			instanceCreateInfo.pNext = &debugUtilsMessengerCI;
		}

		// Enable the debug utils extension if available (e.g. when debugging tools are present)
		if (std::find(supportedInstanceExtensions.begin(), supportedInstanceExtensions.end(), VK_EXT_DEBUG_UTILS_EXTENSION_NAME) != supportedInstanceExtensions.end()) {
			instanceExtensions.push_back(VK_EXT_DEBUG_UTILS_EXTENSION_NAME);
		}

		if (!instanceExtensions.empty()) {
			instanceCreateInfo.enabledExtensionCount = (uint32_t)instanceExtensions.size();
			instanceCreateInfo.ppEnabledExtensionNames = instanceExtensions.data();
		}

		// The VK_LAYER_KHRONOS_validation contains all current validation functionality.
		// Note that on Android this layer requires at least NDK r20
		const char* validationLayerName = "VK_LAYER_KHRONOS_validation";
		//if (settings.validation)
		{
			// Check if this layer is available at instance level
			uint32_t instanceLayerCount;
			vkEnumerateInstanceLayerProperties(&instanceLayerCount, nullptr);
			std::vector<VkLayerProperties> instanceLayerProperties(instanceLayerCount);
			vkEnumerateInstanceLayerProperties(&instanceLayerCount, instanceLayerProperties.data());
			bool validationLayerPresent = false;
			for (VkLayerProperties& layer : instanceLayerProperties) {
				if (strcmp(layer.layerName, validationLayerName) == 0) {
					validationLayerPresent = true;
					break;
				}
			}
			if (validationLayerPresent) {
				instanceCreateInfo.ppEnabledLayerNames = &validationLayerName;
				instanceCreateInfo.enabledLayerCount = 1;
			}
			else {
				std::cerr << "Validation layer VK_LAYER_KHRONOS_validation not present, validation is disabled";
			}
		}

		// If layer settings are defined, then activate the sample's required layer settings during instance creation.
		// Layer settings are typically used to activate specific features of a layer, such as the Validation Layer's
		// printf feature, or to configure specific capabilities of drivers such as MoltenVK on macOS and/or iOS.
		/*VkLayerSettingsCreateInfoEXT layerSettingsCreateInfo{ .sType = VK_STRUCTURE_TYPE_LAYER_SETTINGS_CREATE_INFO_EXT };
		if (enabledLayerSettings.size() > 0) {
			layerSettingsCreateInfo.settingCount = static_cast<uint32_t>(enabledLayerSettings.size());
			layerSettingsCreateInfo.pSettings = enabledLayerSettings.data();
			layerSettingsCreateInfo.pNext = instanceCreateInfo.pNext;
			instanceCreateInfo.pNext = &layerSettingsCreateInfo;
		}*/

		VkInstance instance;
		VkResult result = vkCreateInstance(&instanceCreateInfo, nullptr, &instance);
		if (result != VK_SUCCESS) {
			std::cerr << "Failed to create Vulkan instance!";
			return ERR_SYSTEM_ERROR;
		}
		m_pVkInstance = instance;

		// If the debug utils extension is present we set up debug functions, so samples can label objects for debugging
		if (std::find(supportedInstanceExtensions.begin(), supportedInstanceExtensions.end(), VK_EXT_DEBUG_UTILS_EXTENSION_NAME) != supportedInstanceExtensions.end()) {
			VulkanDebug::setup(instance);
			m_pVkInstance = m_pVkInstance;
		}

		return result;
    }
	AResult VulkanContext::CreatePhysicalDevices()
	{
		// Physical device
		uint32_t gpuCount = 0;
		// Get number of available physical devices
		VkThrowIfFailed(vkEnumeratePhysicalDevices((VkInstance)m_pVkInstance, &gpuCount, nullptr));
		
		if (gpuCount == 0) {
			LOG_ERROR("No device with Vulkan support found");
			return ERR_SYSTEM_ERROR;
		}
		// Enumerate devices
		std::vector<VkPhysicalDevice> physicalDevices(gpuCount);
		VkResult result = vkEnumeratePhysicalDevices((VkInstance)m_pVkInstance, &gpuCount, physicalDevices.data());
		if (result != VK_SUCCESS) {
			LOG_ERROR("Could not enumerate physical devices : %d\n", result);
			return ERR_SYSTEM_ERROR;
		}

		// GPU selection

		// Select physical device to be used for the Vulkan example
		// Defaults to the first device unless specified by command line
		m_pVkPhysicalDevice = (void*)physicalDevices[0];
		return A_Success;
	}
};
