namespace D3D12Utils {
    D3D12_RESOURCE_STATES ConvertResourceState(RESOURCE_STATE state) {
        switch (state) {
        case RESOURCE_STATE_COMMON: return D3D12_RESOURCE_STATE_COMMON;
        case RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER: return D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER;
        case RESOURCE_STATE_INDEX_BUFFER: return D3D12_RESOURCE_STATE_INDEX_BUFFER;
        case RESOURCE_STATE_RENDER_TARGET: return D3D12_RESOURCE_STATE_RENDER_TARGET;
        case RESOURCE_STATE_DEPTH_WRITE: return D3D12_RESOURCE_STATE_DEPTH_WRITE;
        case RESOURCE_STATE_DEPTH_READ: return D3D12_RESOURCE_STATE_DEPTH_READ;
        case RESOURCE_STATE_PIXEL_SHADER_RESOURCE: return D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE;
        case RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE: return D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;
        case RESOURCE_STATE_COPY_SRC: return D3D12_RESOURCE_STATE_COPY_SOURCE;
        case RESOURCE_STATE_COPY_DEST: return D3D12_RESOURCE_STATE_COPY_DEST;
        case RESOURCE_STATE_PRESENT: return D3D12_RESOURCE_STATE_PRESENT;
        default: return D3D12_RESOURCE_STATE_COMMON;
        }
    }
    
    DXGI_FORMAT ConvertFormat(FORMAT format) {
        // 格式转换实现
        switch (format) {
        case FORMAT_R8G8B8A8_UNORM: return DXGI_FORMAT_R8G8B8A8_UNORM;
        case FORMAT_D32_FLOAT: return DXGI_FORMAT_D32_FLOAT;
        // ... 其他格式转换
        default: return DXGI_FORMAT_UNKNOWN;
        }
    }
}